version: '2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
  redis:
    image: redis:3.2
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    depends_on:
      - redis
    ports:
      - "3000:3000"
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
