FROM node:9

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY frontend /usr/src/app

RUN npm install
RUN npm rebuild node-sass

# If we want to build our code for production
# RUN npm install --only=production

CMD ["npm", "run", "start"]

