version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/torimo.io/fullchain.pem:/etc/letsencrypt/live/torimo.io/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/torimo.io/privkey.pem:/etc/letsencrypt/live/torimo.io/privkey.pem
    depends_on:
      - server
  redis:
    image: redis:3.2
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
