version: '2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./takako:/usr/share/nginx
    depends_on:
      - server
  redis:
    image: redis:3.2
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    depends_on:
      - redis
    ports:
      - "3000:3000"
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
