FROM nginx:latest
RUN apt-get update && apt-get install -y nginx-full php7.3-fpm php7.3-mysql php7.3-xml

RUN rm /etc/nginx/conf.d/default.conf
RUN service php7.3-fpm start
COPY nginx.conf /etc/nginx/conf.d
