FROM python:3.6

RUN mkdir -p /opt
COPY takako /opt/takako
COPY notes /opt/notes
COPY requirements.txt /opt/

RUN set -ex; \
    pip install --upgrade pip;

WORKDIR /opt
RUN pip install -r requirements.txt

ENTRYPOINT celery worker -A notes -B --loglevel=debug
