# Generated by Django 2.1.4 on 2018-12-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='owner',
            new_name='user',
        ),
    ]
