# Generated by Django 2.1.4 on 2019-02-24 21:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0007_auto_20181224_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PSProfile',
            new_name='SProfile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='residence',
        ),
    ]
