# Generated by Django 2.1.4 on 2019-05-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
