# Generated by Django 2.1.4 on 2019-05-23 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_itemrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
