# Generated by Django 2.1.4 on 2019-05-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_itemrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
