# Generated by Django 2.1.4 on 2019-07-02 03:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0016_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('card', jsonfield.fields.JSONField()),
                ('charge_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('token_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('item_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.ItemRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='respondent',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
