# Generated by Django 2.1.4 on 2019-07-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0019_auto_20190703_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='item_request',
            new_name='item_request_id',
        ),
    ]
