# Generated by Django 2.1.4 on 2019-07-03 22:22

from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0024_auto_20190703_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', notes.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='charge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.User'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemrequest_requests_created', to='notes.User'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemrequest_requests_received', to='notes.User'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notes.User'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.User'),
        ),
        migrations.AlterField(
            model_name='travelerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notes.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.User'),
        ),
    ]
