# Generated by Django 2.1.4 on 2019-07-06 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0032_auto_20190705_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('dtime', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_phone', models.CharField(blank=True, max_length=100)),
                ('preferred_email', models.CharField(blank=True, max_length=200)),
                ('final_meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purcharse_notification_finalmeetup', to='notes.Meetup')),
                ('item_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purcharse_notification', to='notes.ItemRequest')),
                ('meetup_option1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purcharse_notification_meetup1', to='notes.Meetup')),
                ('meetup_option2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purcharse_notification_meetup2', to='notes.Meetup')),
                ('meetup_option3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purcharse_notification_meetup3', to='notes.Meetup')),
            ],
        ),
    ]
