# Generated by Django 2.1.4 on 2019-07-07 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0033_meetup_purchasenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasenotification',
            name='final_meetup',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purcharse_notification_finalmeetup', to='notes.Meetup'),
        ),
    ]
