# Generated by Django 2.1.4 on 2019-07-07 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0034_auto_20190707_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasenotification',
            name='meetup_option2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purcharse_notification_meetup2', to='notes.Meetup'),
        ),
        migrations.AlterField(
            model_name='purchasenotification',
            name='meetup_option3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purcharse_notification_meetup3', to='notes.Meetup'),
        ),
    ]
