# Generated by Django 2.1.4 on 2019-07-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0037_auto_20190707_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='process_status',
            field=models.CharField(default='request_sent', max_length=100),
        ),
    ]
