# Generated by Django 2.1.4 on 2019-07-30 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0038_itemrequest_process_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_phone', models.CharField(blank=True, max_length=100)),
                ('preferred_email', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='purchasenotification',
            name='action_taken_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharedcontact',
            name='purchase_notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_contact', to='notes.PurchaseNotification'),
        ),
        migrations.AddField(
            model_name='sharedcontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
