# Generated by Django 2.1.4 on 2019-08-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0040_auto_20190802_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='commission_fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='transaction_fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
