# Generated by Django 2.1.4 on 2019-08-08 01:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0042_auto_20190807_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='address',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
