# Generated by Django 2.1.4 on 2019-08-11 03:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0044_auto_20190811_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 8, 11, 3, 8, 27, 461888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 8, 11, 3, 8, 27, 461170, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 8, 11, 3, 8, 27, 462436, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasenotification',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 8, 11, 3, 8, 27, 462999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sharedcontact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 8, 11, 3, 8, 27, 463601, tzinfo=utc)),
        ),
    ]
