# Generated by Django 2.1.4 on 2019-08-11 03:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0045_auto_20190811_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 8, 11, 3, 10, 2, 834811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='charge',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 8, 11, 3, 10, 2, 836180, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 8, 11, 3, 10, 2, 835446, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 8, 11, 3, 10, 2, 836769, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasenotification',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 8, 11, 3, 10, 2, 837398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sharedcontact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 8, 11, 3, 10, 2, 838023, tzinfo=utc)),
        ),
    ]
