# Generated by Django 2.1.4 on 2019-08-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0048_itemrequest_n_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='decline_reason',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='decline_reason_comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
