# Generated by Django 2.1.4 on 2019-08-26 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0050_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
