# Generated by Django 2.1.4 on 2019-08-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0052_auto_20190826_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='meetup_decided_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='meetup_suggested_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='purchase_notified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='responded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
