# Generated by Django 2.1.4 on 2019-09-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0053_auto_20190827_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='item_received_at',
            field=models.DateTimeField(null=True),
        ),
    ]
