# Generated by Django 2.1.4 on 2019-09-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0055_auto_20190914_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_refresh_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
