# Generated by Django 2.1.4 on 2019-09-19 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0056_user_stripe_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, null=True)),
                ('destination', models.CharField(max_length=100)),
                ('stripe_id', models.CharField(max_length=100)),
                ('livemode', models.BooleanField()),
                ('metadata', jsonfield.fields.JSONField()),
                ('object', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='notes.ItemRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
