# Generated by Django 2.1.4 on 2019-09-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0057_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='payment_transferred_at',
            field=models.DateTimeField(null=True),
        ),
    ]
