# Generated by Django 2.1.4 on 2019-09-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0059_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='item_image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
