# Generated by Django 2.1.4 on 2019-11-11 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0062_auto_20191101_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateRequester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('item_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.ItemRequest')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raterequester_reviewee', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raterequester_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateTraveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('item_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.ItemRequest')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratetraveler_reviewee', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratetraveler_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
