# Generated by Django 2.1.4 on 2019-11-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0063_raterequester_ratetraveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='price_per_item',
            field=models.IntegerField(null=True),
        ),
    ]
